DROP TABLE IF EXISTS TBL_EMPLOYEES;
  
CREATE TABLE TBL_FACTS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  LANGUAGE VARCHAR(250) NOT NULL,
  TEXT VARCHAR(250) NOT NULL,
  URL VARCHAR(250) NULL
);

DROP TABLE IF EXISTS FACT;

CREATE TABLE FACTS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  TEXT VARCHAR(250) NOT NULL
);